texts = ['Each section states the economic principle, reviews international good practice and discusses the situation in Brazil. Drawing from international experiences, it concludes with sketching some policy recommendations. The use of such data by the OECD is without prejudice to the status of the Golan Heights, East Jerusalem and Israeli settlements in the West Bank under the terms of international law. A first observation is that regardless of the constitutional setting (federal or unitary), in the most advanced systems, water abstraction charges are commonly managed at sub-national levels.',
 "The “War on Terror” and the Framework of International Law, Helen Duffy, Cambridge: Cambridge University Press, 2005, pp. li, 488.The war on terror poses increasingly intractable challenges for the international legal order. Some commentators query whether the international reaction to 9/11 might have relaxed or transformed well-established legal principles, particularly in the fields of recourse to force and state responsibility. Other scholars opine that international law is adequately suited to address the relatively new and polymorphous threats of terrorism. Regardless of one's stance on the question, it is clear that the current war on terror has generated considerable academic writing, both inside and outside of law, and propelled various legal issues, such as the application of international human rights, international humanitarian law and international criminal law, to the forefront of scholarly inquiry.",
 'The distinction needs to be made between normal risks that are frequent but generate limited damage and catastrophic risks that are rare but have large consequences for individuals or regions. These latter risks should be the main focus of policy actions, keeping in mind the pre-existing policy environment and the whole set of risks affecting the targeted population. Ex ante measures for risk mitigation, in particular income tax smoothing systems for agriculture are also used.',
 'Parents pay a maximum fee for kindergarten only (between 15.8% and 22.5% of total costs in 2011, depending on whether the kindergarten is public or private). Counties are responsible for upper secondary education, which they finance through taxes and block grants. Costs in this sector vary considerably from one region to another. Additional state subsidies and provisions are given to avoid regional disparities. Private kindergartens (50% of all kindergartens) are also financed by the state through the block grants to municipalities.',
 'It does not include activities where the support for the private sector is channelled through public sector agencies e.g. credit lines through state owned banks or challenge funds managed by NGOs, which are covered in the second category. This approach has been used in two previous OECD analyses in Miyamoto and Chiofalo (2015) and Miyamoto and Biousse (2014). This approach has been used in a previous OECD analysis in Brown and Wang (2015).']

from sdg_classifier import classify_sdgs, matched_phrases_per_sdg


if __name__ == "__main__":
    for text in texts:
        print(classify_sdgs(title=text, abstract=None, keywords=None))
        print(matched_phrases_per_sdg(title=text, abstract=None, keywords=None))